production:
    adapter: sqlite3
    database: "<%= (path = ENV['RKN_PRO_DB_DIR']) ? path : 'db' %>/production.sqlite3"
    pool: 50
    timeout: 5000

development:
    host: localhost
    adapter: postgresql
    encoding: unicode
    pool: 100
    username: rkn-pro
    password: <%= ENV['RKN_PRO_PG_PASSWD'] %>
    database: rkn_pro_development

test:
    host: localhost
    adapter: postgresql
    encoding: unicode
    pool: 100
    username: rkn-pro
    password: <%= ENV['RKN_PRO_PG_PASSWD'] %>
    database: rkn_pro_test
