#    $ sudo -u postgres psql
#    postgres=# CREATE USER "scnr-pro" WITH PASSWORD 'secret';
#    postgres=# ALTER USER "scnr-pro" superuser;
production:
    host: localhost
    adapter: postgresql
    encoding: unicode
    pool: 50
    username: scnr-pro
    password: secret
    database: scnr_pro_production
