#    $ sudo -u postgres psql
#    postgres=# CREATE USER "rkn-pro" WITH PASSWORD 'secret';
#    postgres=# ALTER USER "rkn-pro" superuser;
production:
    host: localhost
    adapter: postgresql
    encoding: unicode
    pool: 100
    username: rkn-pro
    password: secret
    database: rkn_pro_production
