production:
    adapter: sqlite3
    database: <%= (path = ENV['SCNR_PRO_DB_DIR']) ? path : 'db' %>/production.sqlite3
    pool: 50
    timeout: 5000

development:
    host: localhost
    adapter: postgresql
    encoding: unicode
    pool: 100
    username: scnr-pro
    password: <%= ENV['SCNR_PRO_PG_PASSWD'] %>
    database: scnr_pro_development

test:
    adapter: sqlite3
    database: <%= (path = ENV['SCNR_PRO_DB_DIR']) ? path : 'db' %>/test.sqlite3
    pool: 50
    timeout: 5000
