production:
    adapter: sqlite3
    database: <%= (path = ENV['SCNR_PRO_DB_DIR']) ? path : 'db' %>/production.sqlite3
    pool: 50
    timeout: 5000

development:
    adapter: sqlite3
    database: <%= (path = ENV['SCNR_PRO_DB_DIR']) ? path : 'db' %>/development.sqlite3
    pool: 50
    timeout: 5000

test:
    adapter: sqlite3
    database: <%= (path = ENV['SCNR_PRO_DB_DIR']) ? path : 'db' %>/test.sqlite3
    pool: 50
    timeout: 5000
