# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  admin_name: First User
  admin_email: admin@admin.admin
  admin_password: administrator
  domain_name: example.com
  secret_key_base: 12ead999060279adc5ffbf8c54f359d98302400a6aba5bdfbb9f5310e21275f6400f2b7649c4658c49b2862be00c1c946ba6ab3ff27596592828db72c8de3b23

test:
  domain_name: example.com 
  secret_key_base: bcb360dcb6772baa48edff4dea14ba5fd3e6410288ff9c5e24138ee1ab65095ca3ba8c4c7f8dd39bcc7d678ab190ee604696fad9376fb7ce82a71dd83d87d0a9

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  admin_name: First User
  admin_email: admin@admin.admin
  admin_password: administrator
  domain_name: example.com
  secret_key_base: 12ead999060279adc5ffbf8c54f359d98302400a6aba5bdfbb9f5310e21275f6400f2b7649c4658c49b2862be00c1c946ba6ab3ff27596592828db72c8de3b23
